In [4]:
# defining necessary libraries
import numpy as np
import pandas as pd
import timeit
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier 
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.model_selection import cross_val_score

In [5]:
# Read corresponding data from dataset and
# keep it as a data frame by pandas library
filename = "C:/Users/Cem/Documents\GitHub/Classification-via-Several-Algorithms/dataset/Frogs_MFCCs.csv"
df = pd.read_csv(filename)
df.head(10)

MFCCs_ 1  MFCCs_ 2  MFCCs_ 3  MFCCs_ 4  MFCCs_ 5  MFCCs_ 6  MFCCs_ 7  \
0       1.0  0.152936 -0.105586  0.200722  0.317201  0.260764  0.100945   
1       1.0  0.171534 -0.098975  0.268425  0.338672  0.268353  0.060835   
2       1.0  0.152317 -0.082973  0.287128  0.276014  0.189867  0.008714   
3       1.0  0.224392  0.118985  0.329432  0.372088  0.361005  0.015501   
4       1.0  0.087817 -0.068345  0.306967  0.330923  0.249144  0.006884   
5       1.0  0.099704 -0.033408  0.349895  0.344535  0.247569  0.022407   
6       1.0  0.021676 -0.062075  0.318229  0.380439  0.179043 -0.041667   
7       1.0  0.145130 -0.033660  0.284166  0.279537  0.175211  0.005791   
8       1.0  0.271326  0.027777  0.375738  0.385432  0.272457  0.098192   
9       1.0  0.120565 -0.107235  0.316555  0.364437  0.307757  0.025992   

   MFCCs_ 8  MFCCs_ 9  MFCCs_10  ...  MFCCs_17  MFCCs_18  MFCCs_19  MFCCs_20  \
0 -0.150063 -0.171128  0.124676  ... -0.108351 -0.077623 -0.009568  0.057684   
1 -0.222475 -0.207693  0.170883  ... -0.090974 -0.056510 -0.035303  0.020140   
2 -0.242234 -0.219153  0.232538  ... -0.050691 -0.023590 -0.066722 -0.025083   
3 -0.194347 -0.098181  0.270375  ... -0.136009 -0.177037 -0.130498 -0.054766   
4 -0.265423 -0.172700  0.266434  ... -0.048885 -0.053074 -0.088550 -0.031346   
5 -0.213767 -0.127916  0.277353  ... -0.080487 -0.130089 -0.171478 -0.071569   
6 -0.252300 -0.167117  0.220027  ... -0.046620 -0.055146 -0.085972 -0.009127   
7 -0.183329 -0.158483  0.192567  ... -0.055978 -0.048219 -0.056637 -0.022419   
8 -0.173730 -0.157857  0.207181  ... -0.120723 -0.112607 -0.156933 -0.118527   
9 -0.294179 -0.223236  0.268435  ... -0.051073 -0.052568 -0.111338 -0.040014   

   MFCCs_21  MFCCs_22           Family      Genus         Species  RecordID  
0  0.118680  0.014038  Leptodactylidae  Adenomera  AdenomeraAndre         1  
1  0.082263  0.029056  Leptodactylidae  Adenomera  AdenomeraAndre         1  
2  0.099108  0.077162  Leptodactylidae  Adenomera  AdenomeraAndre         1  
3 -0.018691  0.023954  Leptodactylidae  Adenomera  AdenomeraAndre         1  
4  0.108610  0.079244  Leptodactylidae  Adenomera  AdenomeraAndre         1  
5  0.077643  0.064903  Leptodactylidae  Adenomera  AdenomeraAndre         1  
6  0.065630  0.044040  Leptodactylidae  Adenomera  AdenomeraAndre         1  
7  0.070085  0.021419  Leptodactylidae  Adenomera  AdenomeraAndre         1  
8 -0.002471  0.002304  Leptodactylidae  Adenomera  AdenomeraAndre         1  
9  0.090204  0.088025  Leptodactylidae  Adenomera  AdenomeraAndre         1  

[10 rows x 26 columns]

# Data Preprocessing 

In [6]:
# delete unnecessary columns
# these columns considered to be not having rich content which
# may be used for later classification purposes (?: tekrar döneceğim buraya)
del df["RecordID"]
del df['Family']
del df['Genus']

# seperate labels and feature columns
X = df.iloc[:, 0:22] # #Takes all rows of all columns except the range 0:22
y = df.select_dtypes(include=[object]) # a subset of the DataFrame’s columns only consisting of objects, which is "species" column

# transforming categorical to numbers
le = preprocessing.LabelEncoder() # Encode target labels with value between 0 and n_classes-1.
y = y.apply(le.fit_transform) # Fit label encoder and return encoded labels

# splitting dataset to train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30)

## Gain ratio

In [ ]:
# ID3 (Iterative Dichotomiser) decision tree algorithm uses information gain.
# C4.5, an improvement of ID3, uses the Gain ratio.
# Training phase
start = timeit.default_timer()
clf_entropy = DecisionTreeClassifier( criterion = "entropy") 
clf_entropy.fit(X_train, y_train)
# Testing phase: predicting X_test values over our model
y_pred_entropy = clf_entropy.predict(X_test)
stop = timeit.default_timer()
print('Runtime of default Gain Ratio: ', stop - start) 

# Evaluating cross validation
# Repeats Stratified K-Fold n times with different randomization in each repetition.
start = timeit.default_timer()
cv_gr1 = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
# Evaluate a score by cross-validation.
# In this case return type: Array of accuracy scores
scores_gr1 = cross_val_score(clf_entropy, X, y, scoring='accuracy', cv=cv_gr1)
stop = timeit.default_timer()
# Comparing results
print("Confusion Matrix: \n", confusion_matrix(y_test, y_pred_entropy)) 
print("Accuracy : ", accuracy_score(y_test, y_pred_entropy)*100)
print("Report: \n", classification_report(y_test, y_pred_entropy))
print('Accuracy (cross validation): %.3f ' % (np.mean(scores_gr1)*100))
print('Runtime of cross-validation applied Gain Ratio: ', stop - start)

# Bagging ensemble method implementation
start = timeit.default_timer()
bagging_model_gr = BaggingClassifier(base_estimator=clf_entropy)
bagging_model_gr.fit(X_train, y_train.values.ravel()) 
cv_gr = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
scores_gr = cross_val_score(bagging_model_gr, X, y.values.ravel(), scoring='accuracy', cv=cv_gr)
bgg_pred_gr = bagging_model_gr.predict(X_test)
stop = timeit.default_timer()
print("Confusion Matrix: \n", confusion_matrix(y_test, bgg_pred_gr)) 
print("Accuracy : ", accuracy_score(y_test, bgg_pred_gr)*100)
print("Report: \n", classification_report(y_test, bgg_pred_gr))
print('Accuracy (cross validation): %.3f ' % (np.mean(scores_gr)*100))
print('Runtime of cross-validation and bagging ensemble applied Gain Ratio: ', stop - start)

# Boosting ensemble method implementation
start = timeit.default_timer()
boosting_model_gr = GradientBoostingClassifier(init=clf_entropy)
boosting_model_gr.fit(X_train, y_train.values.ravel()) 
cv_bst_gr = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
scores_bst_gr = cross_val_score(boosting_model_gr, X, y.values.ravel(), scoring='accuracy', cv=cv_bst_gr)
bst_pred_gr = boosting_model_gr.predict(X_test)
stop = timeit.default_timer()
print("Confusion Matrix: \n", confusion_matrix(y_test, bst_pred_gr)) 
print("Accuracy : ", accuracy_score(y_test, bst_pred_gr)*100)
print("Report: \n", classification_report(y_test, bst_pred_gr))
print('Accuracy (cross validation): %.3f ' % (np.mean(scores_bst_gr)*100))
print('Runtime of cross-validation and boosting ensemble applied Gain Ratio: ', stop - start)

Runtime of default Gain Ratio:  0.2734092000000601
Confusion Matrix: 
 [[ 183    0    6    8    1    0    2    1    1    0]
 [   0 1028    0    6    0    6    1    0    0    1]
 [   5    0  146    3    0    1    0    1    0    0]
 [   2    5    3   84    0    0    0    0    0    2]
 [   3    0    0    1  137    0    1    3    0    1]
 [   2    5    0    3    3  312    5    3    0    2]
 [   2    1    0    3    0    6   66    1    2    0]
 [   1    1    0    1    4    3    3   20    0    0]
 [   0    0    0    0    0    1    0    0   21    0]
 [   0    2    0    3    0    2    0    0    0   39]]
Accuracy :  94.30291801760075
Report: 
               precision    recall  f1-score   support

           0       0.92      0.91      0.92       202
           1       0.99      0.99      0.99      1042
           2       0.94      0.94      0.94       156
           3       0.75      0.88      0.81        96
           4       0.94      0.94      0.94       146
           5       0.94      0.93

## Gini index

In [5]:
start = timeit.default_timer()
clf_gini = DecisionTreeClassifier(criterion = "gini")
clf_gini.fit(X_train, y_train)
y_pred_gini = clf_gini.predict(X_test)
stop = timeit.default_timer()
print('Runtime of default Gini Index: ', stop - start)
start = timeit.default_timer()
cv_gini1 = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
scores_gini1 = cross_val_score(clf_gini, X, y, scoring='accuracy', cv=cv_gini1)
stop = timeit.default_timer()
print("Confusion Matrix: \n", confusion_matrix(y_test, y_pred_gini)) 
print("Accuracy : ", accuracy_score(y_test, y_pred_gini)*100)
print("Report: \n", classification_report(y_test, y_pred_gini))
print('Accuracy (cross validation): %.3f ' % (np.mean(scores_gini1)*100))
print('Runtime of cross-validation applied Gini Index: ', stop - start)

# Bagging ensemble method implementation
start = timeit.default_timer()
bagging_model_gini = BaggingClassifier(base_estimator=clf_gini)
bagging_model_gini.fit(X_train, y_train.values.ravel()) 
cv_gini = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
scores_gini = cross_val_score(bagging_model_gini, X, y.values.ravel(), scoring='accuracy', cv=cv_gini)
bgg_pred_gini = bagging_model_gini.predict(X_test)
stop = timeit.default_timer()
print("Confusion Matrix: \n", confusion_matrix(y_test, bgg_pred_gini)) 
print("Accuracy : ", accuracy_score(y_test, bgg_pred_gini)*100)
print("Report: \n", classification_report(y_test, bgg_pred_gini))
print('Accuracy (cross validation): %.3f ' % (np.mean(scores_gini)*100))
print('Runtime of cross-validation and bagging ensemble applied Gini Index: ', stop - start)

# Boosting ensemble method implementation
start = timeit.default_timer()
boosting_model_gini = GradientBoostingClassifier(init=clf_gini)
boosting_model_gini.fit(X_train, y_train.values.ravel()) 
cv_bst_gini = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
scores_bst_gini = cross_val_score(boosting_model_gini, X, y.values.ravel(), scoring='accuracy', cv=cv_bst_gini)
bst_pred_gini = boosting_model_gini.predict(X_test)
stop = timeit.default_timer()
print("Confusion Matrix: \n", confusion_matrix(y_test, bst_pred_gini)) 
print("Accuracy : ", accuracy_score(y_test, bst_pred_gini)*100)
print("Report: \n", classification_report(y_test, bst_pred_gini))
print('Accuracy (cross validation): %.3f ' % (np.mean(scores_bst_gini)*100))
print('Runtime of cross-validation and boosting ensemble applied Gini Index: ', stop - start)

Runtime of default Gini Index:  0.14654610000002322
Confusion Matrix: 
 [[ 188    0    5    4    2    0    0    2    0    0]
 [   1 1027    2    3    0    2    0    0    2    0]
 [   3    0  152    6    0    5    0    0    1    0]
 [   6    6    5   72    0    1    4    1    0    0]
 [   2    0    0    2  130    2    0    3    0    1]
 [   0    5    0    1    2  317    7    2    0    1]
 [   1    2    0    0    1    5   74    1    4    0]
 [   1    0    0    0    3    3    0   31    0    0]
 [   0    0    0    0    0    0    1    2   12    1]
 [   0    1    0    0    1    7    0    1    0   32]]
Accuracy :  94.25660027790643
Report: 
               precision    recall  f1-score   support

           0       0.93      0.94      0.93       201
           1       0.99      0.99      0.99      1037
           2       0.93      0.91      0.92       167
           3       0.82      0.76      0.79        95
           4       0.94      0.93      0.93       140
           5       0.93      0.9

# Naive Bayes 

In [6]:
start = timeit.default_timer()
gnb = GaussianNB()
gnb.fit(X_train, y_train.values.ravel())
y_pred_gnb = gnb.predict(X_test)
stop = timeit.default_timer()
print("Confusion Matrix: \n", confusion_matrix(y_test, y_pred_gnb)) 
print("Accuracy : ", accuracy_score(y_test, y_pred_gnb)*100)
print("Report: \n", classification_report(y_test, y_pred_gnb))
print('Runtime of default Naive Bayes: ', stop - start)

# Bagging ensemble method implementation
start = timeit.default_timer()
bagging_model_nb = BaggingClassifier(base_estimator=gnb)
bagging_model_nb.fit(X_train, y_train.values.ravel()) 
cv_nb = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
scores_nb = cross_val_score(bagging_model_nb, X, y.values.ravel(), scoring='accuracy', cv=cv_nb)
bgg_pred_nb = bagging_model_nb.predict(X_test)
stop = timeit.default_timer()
print("Confusion Matrix: \n", confusion_matrix(y_test, bgg_pred_nb)) 
print("Accuracy : ", accuracy_score(y_test, bgg_pred_nb)*100)
print("Report: \n", classification_report(y_test, bgg_pred_nb))
print('Runtime of bagging ensemble applied Naive Bayes: ', stop - start)

# Boosting ensemble method implementation
start = timeit.default_timer()
boosting_model_nb = GradientBoostingClassifier(init=gnb)
boosting_model_nb.fit(X_train, y_train.values.ravel()) 
cv_bst_nb = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
scores_bst_nb = cross_val_score(boosting_model_nb, X, y.values.ravel(), scoring='accuracy', cv=cv_bst_nb)
bst_pred_nb = boosting_model_nb.predict(X_test)
stop = timeit.default_timer()
print("Confusion Matrix: \n", confusion_matrix(y_test, bst_pred_nb)) 
print("Accuracy : ", accuracy_score(y_test, bst_pred_nb)*100)
print("Report: \n", classification_report(y_test, bst_pred_nb))
print('Runtime of boosting ensemble applied Naive Bayes: ', stop - start)

Confusion Matrix: 
 [[ 143    0   53    1    1    0    0    3    0    0]
 [   1 1022    0    7    0    1    0    6    0    0]
 [   0    0  167    0    0    0    0    0    0    0]
 [   2    7   33   49    0    0    0    0    0    4]
 [   1    0    0    0  132    0    1    6    0    0]
 [   2    0    0    7    0  299    4   21    0    2]
 [   5    0    4    3    0    1   74    1    0    0]
 [   0    0    1    0    5    3    0   26    3    0]
 [   1    0    0    0    1    0    0    0   14    0]
 [   1    0    3    0    0    0    0    0    1   37]]
Accuracy :  90.92172301991663
Report: 
               precision    recall  f1-score   support

           0       0.92      0.71      0.80       201
           1       0.99      0.99      0.99      1037
           2       0.64      1.00      0.78       167
           3       0.73      0.52      0.60        95
           4       0.95      0.94      0.95       140
           5       0.98      0.89      0.94       335
           6       0.94      0

# Neural networks (1 hidden layer) 

In [7]:
start = timeit.default_timer()
mlp = MLPClassifier(hidden_layer_sizes=(150,), activation='relu', solver='adam', max_iter=1000)
mlp.fit(X_train, y_train.values.ravel())
y_pred_nn = mlp.predict(X_test)
stop = timeit.default_timer()
print("Confusion Matrix: \n", confusion_matrix(y_test, y_pred_nn)) 
print("Accuracy : ", accuracy_score(y_test, y_pred_nn)*100)
print("Report: \n", classification_report(y_test, y_pred_nn))
print('Runtime of default Neural Network: ', stop - start)

# Bagging ensemble method implementation
start = timeit.default_timer()
bagging_model_nn = BaggingClassifier(base_estimator=mlp)
bagging_model_nn.fit(X_train, y_train.values.ravel()) 
cv_nn = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
scores_nn = cross_val_score(bagging_model_nn, X, y.values.ravel(), scoring='accuracy', cv=cv_nn)
bgg_pred_nn = bagging_model_nn.predict(X_test)
stop = timeit.default_timer()
print("Confusion Matrix: \n", confusion_matrix(y_test, bgg_pred_nn)) 
print("Accuracy : ", accuracy_score(y_test, bgg_pred_nn)*100)
print("Report: \n", classification_report(y_test, bgg_pred_nn))
print('Runtime of bagging ensemble applied Neural Network: ', stop - start)

# Boosting ensemble method implementation
start = timeit.default_timer()
boosting_model_nn = GradientBoostingClassifier(init=mlp)
boosting_model_nn.fit(X_train, y_train.values.ravel()) 
cv_bst_nn = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
scores_bst_nn = cross_val_score(boosting_model_nn, X, y.values.ravel(), scoring='accuracy', cv=cv_bst_nn)
bst_pred_nn = boosting_model_nn.predict(X_test)
stop = timeit.default_timer()
print("Confusion Matrix: \n", confusion_matrix(y_test, bst_pred_nn)) 
print("Accuracy : ", accuracy_score(y_test, bst_pred_nn)*100)
print("Report: \n", classification_report(y_test, bst_pred_nn))
print('Runtime of boosting ensemble applied Neural Network: ', stop - start)

Confusion Matrix: 
 [[ 198    0    0    0    0    1    0    2    0    0]
 [   0 1034    0    1    0    1    1    0    0    0]
 [   0    0  165    1    0    1    0    0    0    0]
 [   3    2    2   88    0    0    0    0    0    0]
 [   2    0    0    0  138    0    0    0    0    0]
 [   0    0    0    1    0  329    4    1    0    0]
 [   0    1    0    0    0    1   79    4    3    0]
 [   0    0    0    0    2    0    0   36    0    0]
 [   0    0    0    0    0    0    1    0   15    0]
 [   0    0    0    1    0    1    0    0    0   40]]
Accuracy :  98.28624363131078
Report: 
               precision    recall  f1-score   support

           0       0.98      0.99      0.98       201
           1       1.00      1.00      1.00      1037
           2       0.99      0.99      0.99       167
           3       0.96      0.93      0.94        95
           4       0.99      0.99      0.99       140
           5       0.99      0.98      0.98       335
           6       0.93      0

# Neural networks (2 hidden layers) 

In [8]:
start = timeit.default_timer()
mlp2 = MLPClassifier(hidden_layer_sizes=(75, 75), activation='relu', solver='adam', max_iter=1000)
mlp2.fit(X_train, y_train.values.ravel())
y_pred_nn2 = mlp2.predict(X_test)
stop = timeit.default_timer()
print("Confusion Matrix: \n", confusion_matrix(y_test, y_pred_nn2)) 
print("Accuracy : ", accuracy_score(y_test, y_pred_nn2)*100)
print("Report: \n", classification_report(y_test, y_pred_nn2))
print('Runtime of default Neural Network (2 hidden layers): ', stop - start)

# Bagging ensemble method implementation
start = timeit.default_timer()
bagging_model_nn2 = BaggingClassifier(base_estimator=mlp2)
bagging_model_nn2.fit(X_train, y_train.values.ravel()) 
bgg_pred_nn2 = bagging_model_nn2.predict(X_test)
stop = timeit.default_timer()
print("Confusion Matrix: \n", confusion_matrix(y_test, bgg_pred_nn2)) 
print("Accuracy : ", accuracy_score(y_test, bgg_pred_nn2)*100)
print("Report: \n", classification_report(y_test, bgg_pred_nn2))
print('Runtime of bagging ensemble applied Neural Network (2 hidden layers): ', stop - start)

# Boosting ensemble method implementation
start = timeit.default_timer()
boosting_model_nn2 = GradientBoostingClassifier(init=mlp2)
boosting_model_nn2.fit(X_train, y_train.values.ravel()) 
bst_pred_nn2 = boosting_model_nn2.predict(X_test)
stop = timeit.default_timer()
print("Confusion Matrix: \n", confusion_matrix(y_test, bst_pred_nn2)) 
print("Accuracy : ", accuracy_score(y_test, bst_pred_nn2)*100)
print("Report: \n", classification_report(y_test, bst_pred_nn2))
print('Runtime of boosting ensemble applied Neural Network (2 hidden layers): ', stop - start)

Confusion Matrix: 
 [[ 199    0    0    0    0    1    0    1    0    0]
 [   0 1034    0    1    0    2    0    0    0    0]
 [   0    0  166    0    0    1    0    0    0    0]
 [   3    3    2   87    0    0    0    0    0    0]
 [   1    2    0    0  135    1    0    1    0    0]
 [   0    0    0    1    0  328    5    1    0    0]
 [   2    1    0    0    0    1   79    2    3    0]
 [   0    0    0    0    2    0    0   36    0    0]
 [   0    0    0    0    0    0    1    0   15    0]
 [   0    0    0    1    0    0    0    0    0   41]]
Accuracy :  98.19360815192219
Report: 
               precision    recall  f1-score   support

           0       0.97      0.99      0.98       201
           1       0.99      1.00      1.00      1037
           2       0.99      0.99      0.99       167
           3       0.97      0.92      0.94        95
           4       0.99      0.96      0.97       140
           5       0.98      0.98      0.98       335
           6       0.93      0

# Support Vector Machine 

In [ ]:
# Create the parameter grid based on the results of random search 
start = timeit.default_timer()
params_grid = [{'kernel': ['rbf', 'poly', 'sigmoid', 'linear'], 
                'gamma': [1, 1e-1, 1e-2, 1e-3, 1e-4],
                 'C': [1, 10, 100, 1000]}]
svm_model = GridSearchCV(SVC(), params_grid)
svm_model.fit(X_train, y_train.values.ravel())

final_model = svm_model.best_estimator_
y_pred_final = final_model.predict(X_test)
stop = timeit.default_timer()

print("Confusion Matrix: \n", confusion_matrix(y_test, y_pred_final)) 
print("Report: \n", classification_report(y_test, y_pred_final))
print('Best C:',svm_model.best_estimator_.C) 
print('Best Kernel:',svm_model.best_estimator_.kernel)
print('Best Gamma:',svm_model.best_estimator_.gamma)
print('Best accuracy score :', svm_model.best_score_) 
print("Score (training set): %f" % final_model.score(X_train, y_train))
print("Score (testing set): %f" % final_model.score(X_test, y_test))
print('Runtime of default SVM: ', stop - start)

# Bagging ensemble method implementation
start = timeit.default_timer()
bagging_model_svm = BaggingClassifier(base_estimator=final_model)
bagging_model_svm.fit(X_train, y_train.values.ravel()) 
bgg_pred_svm = bagging_model_svm.predict(X_test)
stop = timeit.default_timer()
print("Confusion Matrix: \n", confusion_matrix(y_test, bgg_pred_svm)) 
print("Accuracy : ", accuracy_score(y_test, bgg_pred_svm)*100)
print("Report: \n", classification_report(y_test, bgg_pred_svm))
print('Runtime of bagging ensemble applied SVM: ', stop - start)

# Boosting ensemble method implementation
start = timeit.default_timer()
boosting_model_svm = GradientBoostingClassifier(init=final_model)
boosting_model_svm.fit(X_train, y_train.values.ravel()) 
bst_pred_svm = boosting_model_svm.predict(X_test)
stop = timeit.default_timer()
print("Confusion Matrix: \n", confusion_matrix(y_test, bst_pred_svm)) 
print("Accuracy : ", accuracy_score(y_test, bst_pred_svm)*100)
print("Report: \n", classification_report(y_test, bst_pred_svm))